[package]
name = "lab5-shaders"
version = "0.1.0"
edition = "2021"
default-run = "lab5-shaders"

[dependencies]
wgpu = "0.19"
winit = "0.29"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
env_logger = "0.11"
